packages:
  # new docs using latest NextJs
  - 'docs'
  # legacy docs using old version NextJs
  - 'next-docs'
  # all packages in subdirs of packages/
  - 'packages/**'
  # all packages in subdirs of workspaces/
  - 'workspaces/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
