export * from './svg/IconAdd';
export * from './svg/IconAllSports';
export * from './svg/IconArrowUp';
export * from './svg/IconArrowRight';
export * from './svg/IconArrowDown';
export * from './svg/IconArrowLeft';
export * from './svg/IconArrowLeftRight';
export * from './svg/IconArrowUpDown';
export * from './svg/IconAsianView';
export * from './svg/IconBitcoinTalk';
export * from './svg/IconBombayClub';
export * from './svg/IconCalendar';
export * from './svg/IconCashOut';
export * from './svg/IconCasino';
export * from './svg/IconChevronDown';
export * from './svg/IconChevronLeft';
export * from './svg/IconChevronRight';
export * from './svg/IconChevronUp';
export * from './svg/IconChevronUpDown';
export * from './svg/IconCircle';
export * from './svg/IconClose';
export * from './svg/IconCurrencyArs';
export * from './svg/IconCurrencyBdt';
export * from './svg/IconCurrencyBob';
export * from './svg/IconCurrencyBrl';
export * from './svg/IconCurrencyBtc';
export * from './svg/IconCurrencyCad';
export * from './svg/IconCurrencyClp';
export * from './svg/IconCurrencyCrc';
export * from './svg/IconCurrencyCny';
export * from './svg/IconCurrencyEth';
export * from './svg/IconCurrencyEur';
export * from './svg/IconCurrencyGel';
export * from './svg/IconCurrencyHkd';
export * from './svg/IconCurrencyIdr';
export * from './svg/IconCurrencyInr';
export * from './svg/IconCurrencyIqd';
export * from './svg/IconCurrencyJpy';
export * from './svg/IconCurrencyKrw';
export * from './svg/IconCurrencyLtc';
export * from './svg/IconCurrencyMxn';
export * from './svg/IconCurrencyMyr';
export * from './svg/IconCurrencyPen';
export * from './svg/IconCurrencyPkr';
export * from './svg/IconCurrencyRub';
export * from './svg/IconCurrencySoc';
export * from './svg/IconCurrencyThb';
export * from './svg/IconCurrencyTrx';
export * from './svg/IconCurrencyTry';
export * from './svg/IconCurrencyUah';
export * from './svg/IconCurrencyUsd';
export * from './svg/IconCurrencyVes';
export * from './svg/IconCurrencyVnd';
export * from './svg/IconDuotoneArrows';
export * from './svg/IconDuotoneChat';
export * from './svg/IconDuotoneCoins';
export * from './svg/IconDuotoneMail';
export * from './svg/IconEdit';
export * from './svg/IconFacebook';
export * from './svg/IconFilter';
export * from './svg/IconFreebet';
export * from './svg/IconGoogle';
export * from './svg/IconHamburger';
export * from './svg/IconHome';
export * from './svg/IconHyperlink';
export * from './svg/IconInPlay';
export * from './svg/IconInstagram';
export * from './svg/IconLeftArrowCurveRight';
export * from './svg/IconLine';
export * from './svg/IconLiveChat';
export * from './svg/IconLogoPlain';
export * from './svg/IconLoyalty0';
export * from './svg/IconMenuHome';
export * from './svg/IconNotification';
export * from './svg/IconNotificationUnread';
export * from './svg/IconPlay';
export * from './svg/IconPriceBoost';
export * from './svg/IconProfile';
export * from './svg/IconSearch';
export * from './svg/IconSettings';
export * from './svg/IconSportsAmericanFootBall';
export * from './svg/IconSportsBadminton';
export * from './svg/IconSportsBaseBall';
export * from './svg/IconSportsBasketBall';
export * from './svg/IconSportsBiathlon';
export * from './svg/IconSportsBoxing';
export * from './svg/IconSportsCricket';
export * from './svg/IconSportsCycling';
export * from './svg/IconSportsDarts';
export * from './svg/IconSportsESports';
export * from './svg/IconSportsFootBall';
export * from './svg/IconSportsGolf';
export * from './svg/IconSportsHandBall';
export * from './svg/IconSportsHorseRacing';
export * from './svg/IconSportsIceHockey';
export * from './svg/IconSportsMma';
export * from './svg/IconSportsMotorSports';
export * from './svg/IconSportsPolitics';
export * from './svg/IconSportsPool';
export * from './svg/IconSportsPopular';
export * from './svg/IconSportsRugby';
export * from './svg/IconSportsSki';
export * from './svg/IconSportsSnooker';
export * from './svg/IconSportsSpecial';
export * from './svg/IconSportsSquash';
export * from './svg/IconSportsTableTennis';
export * from './svg/IconSportsTennis';
export * from './svg/IconSportsVolleyBall';
export * from './svg/IconSportsWaterPolo';
export * from './svg/IconStats';
export * from './svg/IconSuccess';
export * from './svg/IconTelegram';
export * from './svg/IconTwitter';
export * from './svg/IconUpload';
export * from './svg/IconVkontakte';
export * from './svg/IconWarning';
export * from './svg/IconYoutube';
export * from './svg/IconSbShield';

export * from './backgrounds/Background1';
export * from './backgrounds/IconSuccessFlower';
export * from './backgrounds/IconWarningExclamation';

/**
 * ⚠ DEPRECATED
 * Please use an un-aliased icon.
 * @TODO Delete in next major version.
 */
export { IconCurrencyBtc as IconBitcoin } from './svg/IconCurrencyBtc';
export {
  IconSportsHorseRacing as IconHorseRacing,
} from './svg/IconSportsHorseRacing';
export { IconCurrencyEur as IconEuro } from './svg/IconCurrencyEur';
export { IconDuotoneArrows as IconExchange } from './svg/IconDuotoneArrows';
export { IconDuotoneChat as IconMessage } from './svg/IconDuotoneChat';
export { IconDuotoneCoins as IconCoins } from './svg/IconDuotoneCoins';
export { IconLoyalty0 as IconLoyality0 } from './svg/IconLoyalty0';
export { IconSportsSnooker as IconSportsSinuca } from './svg/IconSportsSnooker';
export { IconSportsFootBall as IconSoccer } from './svg/IconSportsFootBall';
