export type Brand =
  | 'Sportsbet.io'
  | 'Bitcasino.io'
  | 'Comms'
  | 'Slots.io'
  | 'LuckySlots'
  | 'BombayClub'
  | 'Livecasino.io'
  | 'Hub88'
  | 'Aposta10'
  | 'BTCXE'
  | 'MissionsTool'
  | 'Moneyball'
  | 'MoonDesign'
  | 'ShangriLa.io';
