const styledComponents = [
  { name: 'Accordion', href: '/styledComponents/accordion' },
  { name: 'AuthCode', href: '/styledComponents/authCode' },
  { name: 'Avatar', href: '/styledComponents/avatar' },
  { name: 'Banner', href: '/styledComponents/banner' },
  { name: 'Button', href: '/styledComponents/button' },
  { name: 'Carousel', href: '/styledComponents/carousel' },
  { name: 'Geo map', href: '/styledComponents/charts/geoMapChart' },
  { name: 'Line', href: '/styledComponents/charts/lineChart' },
  { name: 'Pie', href: '/styledComponents/charts/pieChart' },
  { name: 'Table', href: '/styledComponents/charts/tableChart' },
  { name: 'Vertical bar', href: '/styledComponents/charts/verticalBarChart' },
  { name: 'Checkbox', href: '/styledComponents/checkbox' },
  { name: 'Chip', href: '/styledComponents/chip' },
  { name: 'Range', href: '/styledComponents/datepickerRange' },
  { name: 'Single Date', href: '/styledComponents/datepicker' },
  { name: 'Dialog Content', href: '/styledComponents/dialog/dialogContent' },
  { name: 'Dialog Footer', href: '/styledComponents/dialog/footer' },
  { name: 'Dialog Header', href: '/styledComponents/dialog/header' },
  { name: 'Dialog Overlay', href: '/styledComponents/dialog/dialogOverlay' },
  { name: 'Dialog', href: '/styledComponents/dialog/dialog' },
  { name: 'Popover', href: '/styledComponents/popover' },
  { name: 'Icons', href: '/styledComponents/icons' },
  { name: 'Label', href: '/styledComponents/label' },
  { name: 'List Item', href: '/styledComponents/listItem' },
  { name: 'Loader', href: '/styledComponents/loader' },
  { name: 'Pagination', href: '/styledComponents/pagination' },
  { name: 'Circular', href: '/styledComponents/progress/circular' },
  { name: 'Linear', href: '/styledComponents/progress/linear' },
  { name: 'RadioButton', href: '/styledComponents/radiobutton' },
  { name: 'Search', href: '/styledComponents/search' },
  {
    name: 'Multi Select',
    href: '/styledComponents/select/multiSelect',
  },
  { name: 'Select', href: '/styledComponents/select/select' },
  {
    name: 'Single Select',
    href: '/styledComponents/select/singleSelect',
  },
  { name: 'Switch', href: '/styledComponents/switch' },
  { name: 'Table', href: '/styledComponents/table' },
  { name: 'Tabs', href: '/styledComponents/tabs' },
  { name: 'TextInput Group', href: '/styledComponents/textInputGroup' },
  { name: 'Date Time', href: '/styledComponents/textInput/dateTime' },
  { name: 'Date', href: '/styledComponents/textInput/date' },
  { name: 'Email', href: '/styledComponents/textInput/email' },
  { name: 'Number', href: '/styledComponents/textInput/number' },
  { name: 'Password', href: '/styledComponents/textInput/password' },
  { name: 'Search', href: '/styledComponents/textInput/search' },
  { name: 'Telephone', href: '/styledComponents/textInput/telephone' },
  { name: 'Text', href: '/styledComponents/textInput/text' },
  { name: 'Time', href: '/styledComponents/textInput/time' },
  { name: 'Url', href: '/styledComponents/textInput/url' },
  { name: 'Tooltip', href: '/styledComponents/tooltip' },
  { name: 'Caption', href: '/styledComponents/typography/caption' },
  { name: 'Heading', href: '/styledComponents/typography/heading' },
  { name: 'Text', href: '/styledComponents/typography/text' },
];

export default styledComponents;
